# Generated by Django 5.2.9 on 2026-01-06 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_types', models.JSONField(blank=True, default=list, help_text="List of vehicle types handled, e.g., ['car', 'bike']")),
                ('timings', models.JSONField(blank=True, default=dict, help_text="e.g., {'monday': '9am-5pm', 'tuesday': '9am-5pm', ...}")),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list or description of amenities (e.g., WiFi, Waiting Area)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_issues', models.JSONField(blank=True, default=list, help_text="List of car issues handled, e.g., ['engine_failure', 'battery_dead']")),
                ('bike_issues', models.JSONField(blank=True, default=list, help_text='List of bike issues handled')),
                ('other_issues', models.JSONField(blank=True, default=list, help_text='List of other vehicle issues handled')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_location', to='core.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repair Shop',
                'verbose_name_plural': 'Repair Shops',
            },
        ),
        migrations.CreateModel(
            name='TowingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_types', models.JSONField(blank=True, default=list, help_text="List of vehicle types handled, e.g., ['car', 'bike']")),
                ('timings', models.JSONField(blank=True, default=dict, help_text="e.g., {'monday': '9am-5pm', 'tuesday': '9am-5pm', ...}")),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list or description of amenities (e.g., WiFi, Waiting Area)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('towing_types', models.TextField(blank=True, help_text='e.g., Flatbed Towing, Wheel-Lift Towing, Heavy-Duty Towing')),
                ('response_time', models.CharField(blank=True, help_text='Average response time (e.g., 30 minutes)', max_length=50)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_location', to='core.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Towing Provider',
                'verbose_name_plural': 'Towing Providers',
            },
        ),
    ]
